document.addEventListener('DOMContentLoaded',()=>{const q=(s,c=document)=>c.querySelector(s),qa=(s,c=document)=>[...c.querySelectorAll(s)];
const progress=document.createElement('div');progress.className='reading-progress';document.body.prepend(progress);const updateProgress=()=>{const total=document.documentElement.scrollHeight-innerHeight;progress.style.width=(total>0?scrollY/total*100:0)+'%'};addEventListener('scroll',updateProgress,{passive:true});updateProgress();
const menu=q('.menu-toggle'),nav=q('.nav-links');if(menu&&nav){menu.setAttribute('aria-label','Abrir menu');menu.onclick=()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open))};qa('a',nav).forEach(a=>a.onclick=()=>nav.classList.remove('open'));document.addEventListener('click',e=>{if(!nav.contains(e.target)&&!menu.contains(e.target))nav.classList.remove('open')})}
qa('[data-filter]').forEach(b=>b.onclick=()=>{qa('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const f=b.dataset.filter;qa('[data-category]').forEach(c=>c.hidden=f!=='all'&&!c.dataset.category.includes(f))});
qa('.carousel').forEach(c=>{const track=q('.carousel-track',c),slides=qa('.carousel-slide',c),dots=q('.carousel-dots',c);if(!track||!slides.length)return;let i=0;const go=n=>{i=(n+slides.length)%slides.length;track.style.transform=`translateX(-${i*100}%)`;qa('button',dots).forEach((d,k)=>d.classList.toggle('active',k===i))};slides.forEach((_,k)=>{const d=document.createElement('button');d.setAttribute('aria-label',`Imagem ${k+1}`);d.onclick=()=>go(k);dots?.append(d)});q('.prev',c)?.addEventListener('click',()=>go(i-1));q('.next',c)?.addEventListener('click',()=>go(i+1));go(0)});
qa('.gallery img,.media-tile img').forEach(img=>img.onclick=()=>{const l=document.createElement('div');l.className='lightbox';l.innerHTML=`<button aria-label="Fechar">×</button><img src="${img.src}" alt="${img.alt||''}">`;l.onclick=e=>{if(e.target===l||e.target.tagName==='BUTTON')l.remove()};document.body.append(l)});
qa('.accordion button').forEach(b=>b.onclick=()=>b.parentElement.classList.toggle('open'));qa('[data-copy]').forEach(b=>b.onclick=async()=>{await navigator.clipboard.writeText(b.dataset.copy);const old=b.textContent;b.textContent='Link copiado';setTimeout(()=>b.textContent=old,1400)});
const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.08});qa('section,.card,.smart-card,.media-tile,.feature-panel').forEach(x=>{x.classList.add('reveal');io.observe(x)});
const path=location.pathname,root=path.includes('/cases/')?'../':'',dock=document.createElement('nav');dock.className='mobile-dock';dock.setAttribute('aria-label','Navegação rápida');const current=path.split('/').pop()||'index.html';dock.innerHTML=`<a data-icon="home" href="${root}index.html">Início</a><a data-icon="work" href="${root}tech.html">Projetos</a><a data-icon="about" href="${root}sobre.html">Sobre</a><a data-icon="contact" href="${root}contato.html">Contato</a>`;qa('a',dock).forEach(a=>{const href=a.getAttribute('href').split('/').pop();if(current===href||(path.includes('/cases/')&&href==='tech.html'))a.classList.add('active')});document.body.append(dock);
const slug=current.replace('.html',''),cases={
'okan-nexus':['Centralizar indicadores, tarefas e visão operacional em um dashboard.','Validar navegação, KPIs e fluxos prioritários.','Construir um MVP com componentes reutilizáveis.','Reduzir dispersão de dados e apoiar decisões.','Entregar e validar o MVP em cinco semanas.'],
'cv-builder':['Simplificar a criação de currículos profissionais.','Permitir edição, prévia e geração estruturada.','Usar formulários, validações e componentes web.','Reduzir esforço e inconsistência nas candidaturas.','Testar a primeira versão em quatro semanas.'],
'digital-bank':['Modelar clientes, contas e operações bancárias.','Implementar entidades, transações e regras testáveis.','Aplicar Java e POO em escopo acadêmico controlado.','Demonstrar domínio de regras de negócio bancárias.','Finalizar o desafio em duas semanas.'],
'global-growth':['Estruturar campanhas para mercados internacionais.','Organizar públicos, canais, criativos e indicadores.','Executar ciclos de mídia e otimização com os recursos disponíveis.','Aumentar consistência global com adaptação local.','Planejar trimestralmente e otimizar semanalmente.'],
'ecommerce-growth':['Melhorar a jornada do e-commerce.','Mapear fricções e acompanhar conversão.','Priorizar melhorias incrementais em Shopify.','Apoiar crescimento comercial e clareza da experiência.','Executar roadmap de 30, 60 e 90 dias.'],
'influencer-program':['Estruturar afiliados, influenciadores e comunidade.','Definir entrada, ativação e acompanhamento.','Usar CRM, conteúdo e processos escaláveis.','Transformar relações dispersas em comunidade de marca.','Estruturar a operação inicial em oito semanas.'],
'landing-page':['Criar uma landing page marcante e orientada à conversão.','Validar narrativa, CTA, responsividade e hierarquia.','Desenvolver em página única com HTML e CSS.','Traduzir oferta e posicionamento em experiência persuasiva.','Concluir conceito e desenvolvimento em duas semanas.'],
'brand-campaigns':['Criar um sistema visual para campanhas e lançamentos.','Entregar conceito, paleta, tipografia e aplicações.','Combinar direção criativa, Figma e Adobe.','Aumentar consistência e percepção de valor da marca.','Desenvolver campanhas em ciclos de três a seis semanas.'],
'ux-digital':['Desenhar interfaces claras, acessíveis e consistentes.','Produzir fluxos, wireframes e protótipos testáveis.','Aplicar pesquisa, arquitetura de informação e iteração.','Reduzir fricção e melhorar compreensão do produto.','Executar discovery e protótipo em duas a quatro semanas.']};
if(path.includes('/cases/')&&cases[slug]&&!q('.smart-grid')){const d=cases[slug],sec=document.createElement('section');sec.className='section';sec.innerHTML=`<div class="container"><div class="section-head"><span class="section-label">OBJETIVO SMART</span><h2>Decisão com critério e prazo</h2><p>Cada dimensão transforma intenção em uma entrega verificável.</p></div><div class="smart-grid">${[['S','Specific — Específico',d[0]],['M','Measurable — Mensurável',d[1]],['A','Achievable — Atingível',d[2]],['R','Relevant — Relevante',d[3]],['T','Time-bound — Temporal',d[4]]].map(x=>`<article class="smart-card"><div class="smart-letter">${x[0]}</div><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join('')}</div></div>`;(q('.case-hero')||q('header'))?.after(sec)}
});